@startuml
class TopicLine {
    - url
    - line
    - description
}
class Topic {
    - name
    - datetime
}

class TopicLineService {
    - topics
    - addTopicLine(Topic)
    - removeTopicLine()
    - addTopicLine()
    - removeTopic()

    - getState()
    - loadState() 
}

class OpenFileDescriptor {
    - getLine()
}

class StartupActivity

class State
note right of State
   topicLine
     - topicId
     - url
     - line
     - description
   topic
     - id
     - name 
end note

package idea {
    class FileEditor
    class VirtualFile

    class Document
    class DocumentMarkupModel
    class RangeHighLighter

    interface FileEditorManagerListener

    Document o- DocumentMarkupModel
    DocumentMarkupModel o- RangeHighLighter

    VirtualFile ..> Document : load
}


package ui {
    class ToolWindow
    class TopicListView

    ToolWindow o- TopicListView
}

package actions {
    class ToggleAction
    class OpenToolWindowAction
}

/' relation '/
Topic o- TopicLine
TopicLine -- VirtualFile
TopicLine - OpenFileDescriptor
TopicLine -- RangeHighLighter

TopicLineService o-- Topic
TopicLineService - State

TopicLine -- TopicListView

OpenToolWindowAction ..> ToolWindow : open

StartupActivity ..> TopicLineService : initialize

@enduml