@startuml
class TopicLine {
    - url
    - line
    - description
}
class Topic {
    - name
    - datetime
}

class TopicList {
    - addTopicLine(Topic)
    - removeTopicLine()
    - addTopicLine()
    - removeTopic()
}

class CodeReadingRecorderService {
  - project
  - topicList
  - JBPopup popup

  - getState()
  - loadState()
}

note right of CodeReadingRecorderService
   state format is..
   topicLine
     - topicId
     - url
     - line
     - description
   topic
     - id
     - name
end note

class OpenFileDescriptor {
    - getLine()
}

class StartupActivity


package idea {
    class FileEditor
    class VirtualFile

    class Document
    class DocumentMarkupModel
    class RangeHighLighter

    interface FileEditorManagerListener

    Document o- DocumentMarkupModel
    DocumentMarkupModel o- RangeHighLighter

    VirtualFile ..> Document : load
}

package ui {
    class ManagementPopupBuilder
}

package actions {
    class ToggleAction
    class OpenToolWindowAction
}


/' relation '/
StartupActivity ..> CodeReadingRecorderService : initialize
CodeReadingRecorderService o-- TopicList

TopicList o-- Topic
Topic o- TopicLine

TopicLine -- VirtualFile
TopicLine - OpenFileDescriptor
TopicLine -- RangeHighLighter

TopicLine -- TopicListView

OpenToolWindowAction ..> ToolWindow : open

@enduml