@startuml
/' definition '/
participant ToolWindow
participant NewTopicDialogOpenAction
participant TopicList
participant Messages


/' flow '/
ToolWindow -> NewTopicDialogOpenAction : perform

NewTopicDialogOpenAction -> Messages : showInputDialog
return topic name

create Topic
NewTopicDialogOpenAction -> Topic : new
NewTopicDialogOpenAction -> TopicList : addTopic(topic)
@enduml